### ISSUE TITLE
Confluence Custom Field does not Display on JIRA Issues Confluence Macro Table

### ISSUE THREAD

**Issue by yusuftambag** [mesilat/confluence-fields#1] opened 2020-08-17 13:35 UTC
Hi,

I've a confluence cf in JIRA field value shown in JIRA without any problem but when we use JIRA macro within confluence , custom field value not shown in confluence JIRA macro table. We need help urgently, could you please help me if there is any workaround solution, images clarifying the problem attached.

-thank you very much
-yusuf
![confluence_field_jira_jql](https://user-images.githubusercontent.com/24789638/90402124-a9bb3500-e0a7-11ea-9b60-bab8ea0d2ce8.png)
![conf_field_jira_macro](https://user-images.githubusercontent.com/24789638/90402126-aa53cb80-e0a7-11ea-8941-51f0f1440ac9.png)

**Comment by vb-mesilat** [comment] 2020-08-17 22:10
Hi, yusuftambag

Thanks for reporting the issue. I think I know the cause of the problem. It will take a day or two to create a new release that will fix the issue. Please note, however, that it is not possible to display the value as a page link -- JIRA macro of Confluence does not provide for this kind of functionality. So, the value will be a page title (or a list of page titles) in plain text.

**Comment by yusuftambag** [comment] 2020-08-18 07:08
Hi,

I've realized that the İ character was causing the problem when I change it to I it was ok. But unfortunately team reported me that they nedd link, so I need to write my own macro.

-thank you very much
-yusuf

**Comment by vb-mesilat** [comment] 2020-08-18 08:50
Wow! That's interesting. I will check this. Thanks a lot

**Comment by yusuftambag** [comment] 2020-08-18 14:01
Hi Vladislav,

Actually problem is not related with your plugin, other custom fields whose name contains İ also returns empty values for the macro. We have also some other problems with confluence caused by İ character.

-thank you very mych
-yusuf

**Comment by vb-mesilat** [comment] 2020-08-18 16:28
Wow! I guess I can close the issue in that case

Regards,

**Closed as completed by vb-mesilat** 2020-08-18 16:28 UTC
