### ISSUE TITLE
Customer Service Desk page not render

### ISSUE THREAD

**Issue by cascador84** [mesilat/confluence-fields#14] opened 2020-02-28 08:04 UTC
Dear  Support,
 
We encountered an annoying bug after installing your add-on (latest version) on our Jira (latest version) server
Indeed, before installation (or after disabling the add-on), we can render Customer page (all visuals are display, issue data are displayed...)

After installation, the same page will no longer render:

![image](https://user-images.githubusercontent.com/61578358/75521952-1747ac00-5a09-11ea-865e-08cd201396bb.png)

After further investigation, I see some differences on source code for the same page (before installing / enabling add-on and after) :
 
Page correctly render / add-on disable / not installed:
 `<!DOCTYPE html><html lang="en-US" class="aui-responsive">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EDGE"/>
 
<script>window.ULTIMATE_INITIAL_CONTEXT = […]
</script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=EDGE">
[…]`
 

Page not render / add-on enable:
 `<!DOCTYPE html><html lang="en-US" class="aui-responsive">
<head>
 
 
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=EDGE">
[…]`

It seems enabling add-on replace / avoid / cut some header meta text on page. Are you aware about this kind of behaviour ?
 
Jira v.8.50
Jira Service desk 4.5.0
Confluence Custom fields 1.0.23

Regards,
Xavier

**Comment by mesilat** [comment] 2020-02-28 21:35
Hi, Xavier

I did some more testing and found a possible cause. Please install version 1.0.24 and let me know if this resolves the issue.
If not please disable the plugin until I prepare test set matching your environment.

Regards
Vladislav

**Comment by cascador84** [comment] 2020-03-02 07:04
Hi Vladislav,
sorry, but the update didn't solve the issue.
stille have same problem.

I try to create a new Jira issue after upgrade, but always not rendering.


regards,
Xavier

**Comment by mesilat** [comment] 2020-03-02 11:17
Too bad. Unfortunately I am out of office until Monday. You can disable portal.js component of the plugin until I finally fix the problem. Also please try another browser to make sure that the erroneous code is not cached.

**Comment by mesilat** [comment] 2020-03-16 06:38
Hi, I have tested the plugin with clean JSD 4.5.0 install and was not able to find any problem. My Confluence Custom Fields plugin version is 1.0.24

If you still have interest in using the plugin with Customer Portal please clear your browser cache or test with different browser. If the problem persists I need more logs from your browser to further investigate the problem.

Regards,
Vladislav

**Comment by mesilat** [comment] 2020-04-09 19:22
No feedback from reporter. Closing

**Closed by mesilat** 2020-04-09 19:22 UTC

**Comment by cascador84** [comment] 2020-05-19 07:20
Dear Vladislav.
After updating your plugin to 1.0.26, I check our Customer portal tickets, and now, seems display correctly. I will make some other test, but in a first view, it seems solved.

Thanks for all !!
Regards,

**Comment by mesilat** [comment] 2020-05-19 18:17
Hi,Thanks for your feedback! That's good to know that the issue is resolvedBest regards,Vladislav BabinMesilat Limited19.05.2020, 10:20, "cascador84" <notifications@github.com>:
Dear Vladislav.
After updating your plugin to 1.0.26, I check our Customer portal tickets, and now, seems display correctly. I will make some other test, but in a first view, it seems solved.
Thanks for all !!
Regards,

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Best regards,Mesilat Limited Teamsupport@mesilat.com
