### ISSUE TITLE
Improved CQL Filter definition

### ISSUE THREAD

**Issue by gcuny** [mesilat/confluence-fields#2] opened 2019-05-29 10:30 UTC
This APP has (some of) the functionality, I have been looking for.
It would be great to be able to refer to the content of other Jira fields (text, option, select, ....) in the CQL filter definition.

**Comment by mesilat** [comment] 2019-05-29 13:48
I think this could be done. I guess I could add a reference to issue fields like ${key}, ${summary} etc
Will schedule this for next release

**Comment by gcuny** [comment] 2019-05-29 13:54
That would be great. Please allow references to custom fields as well, for example ${customfield_#####}.

**Comment by mesilat** [comment] 2019-05-31 07:20
Please check version 1.0.1 -- https://github.com/mesilat/confluence-fields/releases/tag/1.0.1
I would appreciate your comments before I publish this to Atlassian marketplace.

You can use the following substitution variables:

- ${id} (issue id)
- ${key} (issue key)
- fields (issue summary, issuetype, project, customfield_... etc -- whatever is returned by JIRA API "/rest/api/2/issue/{issueKey}")

When using object fields (such as issuetype or project) you should address certain properties, for example:

- ${issuetype.name}
- ${project.projectTypeKey}

To reference custom fields of type 'Confluence Field' keep in mind that the value of the field is an array. Thus, to reference single value you should use something like `${customfield_11204[0].id}` or `${customfield_11204[0].title}`

Let me know if this works for you

**Comment by gcuny** [comment] 2019-05-31 12:27
Thank you very much for the Version 1.0.1.

The filter
space = "UM" and  label in (191, 192, 193)
returns correct results in the Test field.

The values 191, 192 and 193 are labels used on some Confluence pages.

.../rest/api/2/issue/256361 returns:

	"customfield_13520":       {
	 "self": "https://jira-test-2.gipmbh.de/rest/api/2/customFieldOption/12004",
	 "value": "191",
	 "id": "12004"
	},
	
The customfield_13520 is a Select List field (exactly: a "Secure List" field from the APP: Secure Fields, CoreSoft Labs, Version 3.0.4-jira72).

I tried the following filter in the "Confluence Field" configuration:
space = "UM" and label = ${customfield_13520[0].value}
The Test returns: Could not parse cql : type="page" and space = "UM" and label = ${customfield_13520[0].value}
That seems to be quite logical, because the value of the customfield_13520 can only be retrieved for a specific issue. So, in order to be able to test a filter containing issue fields, it should be possible to tell the system, for which specified issue the test should be performed.
Assuming the filter should be OK, I tried my Confluence Field in a Jira Screen: it was searching, but didn't return a result. 

The filter
space = "UM" and  label = ${customfield_13520.value}
returns: Invalid label: "customfield_13520.value".

The filter
space = "UM" and  label = ${customfield_13520.stringvalue}
doesn't return any results in the Test field but returns valid results on my screen, if I use the id=12004 instead of the assigned value=191 in the customfield_13520.

**Comment by mesilat** [comment] 2019-05-31 14:39
Please try CQL 
`space = "UM" and label = "${customfield_13520}"`

**Comment by gcuny** [comment] 2019-05-31 14:44
Sorry, no results with this CQL.

**Comment by mesilat** [comment] 2019-05-31 17:49
What type is this custom field? You can check by appending "?expand=schema" to your API call, ex:

`.../rest/api/2/issue/256361?expand=schema`

Can you post or PM full response?

**Comment by mesilat** [comment] 2019-06-02 08:28
I also added support for textarea and select (in case referenced custom field is not <input>), please try version 1.0.2

**Comment by gcuny** [comment] 2019-06-03 09:10
Please find attached my Feedback to the verion 1.0.2.
[Feedback_01-Version_1.0.2.pdf](https://github.com/mesilat/confluence-fields/files/3246771/Feedback_01-Version_1.0.2.pdf)

**Comment by gcuny** [comment] 2019-06-03 09:10
Sorry

**Comment by mesilat** [comment] 2019-06-03 21:10
Thanks for detailed report.
The root problem is actually as follows: the API returns custom field value as an object (similar to what you posted above). However select control does not hold an object but a single value. For example, API returns 

```
"customfield_13520":       {
 "self": "https://jira-test-2.gipmbh.de/rest/api/2/customFieldOption/12004",
 "value": "191",
 "id": "12004"
},
```

But select control `$('#customfield_13520').val()` will only return "12004".

Thus your CQL `space = "UM" and label = ${customfield_13520.value}` will work as expected when editing confluence-backed field 'in-place' (in an issue view). But to get it work with edit view it must first be converted to an object using `/rest/api/2/customFieldOption/{optionid}` API.

I will fix and post a new release.

**Comment by mesilat** [comment] 2019-06-04 05:37
Please try version 1.0.3

Note that using substitution variable that references a single-select field requires `.value` suffix.

For example if customfield_11204 is a single select control than referencing it in CQL filter would be something similar to:
```
label = "${customfield_11204.value}"
```

**Comment by gcuny** [comment] 2019-06-04 08:50
Thank you for Version 1.0.3.
Unfortunately there is no improvement with this version to version 1.0.2.
The CQL label = "${customfield_#####.value}" behaves just the way the CQL label = $customfield_#####.vule} does.

I am not a programmer, but I wrote some Groovy Code for post functions in our workflows. See the example below, where I access the original values of an issue and the new values during a transition. Hopefully that might help you:

import com.atlassian.jira.component.ComponentAccessor
import com.atlassian.jira.issue.Issue	

Issue issue = issue

def customFieldManager = ComponentAccessor.getCustomFieldManager()
def issueManager = ComponentAccessor.getIssueManager()
def originalIssue = issueManager.getIssueObject(issue.id)

def title = "*Änderung von Vorganstyp und/oder Priorität* (siehe auch Änderungshistorie)"
def typ = "\nVorgangstyp: " + originalIssue.issueType.name + " ---> " + issue.issueType.name
def prio = "\nPriorität: " + originalIssue.priority.name + " ---> " + issue.priority.name
transientVars['comment'] =  title + typ + prio + "\n" + transientVars['comment']

**Comment by mesilat** [comment] 2019-06-04 12:32
This is a little different as Groovy runs at server side, while plugin accesses data via REST API.

Please try ver 1.0.4. It is only different from 1.0.3 in a way it prints debugging information to browser console. I need to take a look at your browser logs, specifically the ones that use prefix "com-mesilat-confields", could you please post them here?

**Comment by gcuny** [comment] 2019-06-04 14:20
Please find attached some log files tracking the display of a ticket, opening a transition screen, clicking into the confluence field (Update), changing the selection in a select field (customfield_13520) and clicking into the confluence field again.

I'm really willing to support you with tests in my environme
[BrowserLog_03_Chrome_Version_1.0.4.log](https://github.com/mesilat/confluence-fields/files/3252860/BrowserLog_03_Chrome_Version_1.0.4.log)
[BrowserLog_01_Edge_Version_1.0.4.txt](https://github.com/mesilat/confluence-fields/files/3252861/BrowserLog_01_Edge_Version_1.0.4.txt)
[BrowserLog_02_Edge_Version_1.0.4.txt](https://github.com/mesilat/confluence-fields/files/3252862/BrowserLog_02_Edge_Version_1.0.4.txt)


nt, but wouldn't it be much easier and far more efficient for you to debug the app in an environment of your own?

**Comment by mesilat** [comment] 2019-06-04 19:40
> but wouldn't it be much easier and far more efficient for you to debug the app in an environment of your own?

Definitely so. But in my environment it works fine ;)

**Comment by mesilat** [comment] 2019-06-04 20:06
Thanks for the logs! In Chrome I could see nothing of interest, but in Edge there's the record that I was interested in:

> com-mesilat-confields updateField() filterFields:  {"customfield_13520.value":"192"}

This is what goes from your browser to backend for substitution variables. And this is what supposed to be used in CQL. So, I am at loss right now what could go wrong here.

I think I could add some more server-side logging to trace communication between Confluence and JIRA. That is if you are still willing to participate, of course

**Comment by mesilat** [comment] 2019-06-04 20:28
Ver 1.0.5 adds CQL tracing. To log request/response enable DEBUG or ALL logging for `com.mesilat.confluence-fields`

**Comment by gcuny** [comment] 2019-06-05 06:43
Of course, I am still willing to participate and to support you with my tests and my feedback, because your confluence-fields APP might become very helpful for my use cases. You'll hear/read from me later today or tomorrow.
Regards, Georges

**Comment by gcuny** [comment] 2019-06-05 14:13
To avoid potential problems with the secure select list I changed the type of 'LT Release' to the normal jira native select list. Attached you find the requested log-file.
[v1.0.5_atlassian-jira.log](https://github.com/mesilat/confluence-fields/files/3257556/v1.0.5_atlassian-jira.log)

**Comment by mesilat** [comment] 2019-06-05 17:30
I see from the log that Confluence returns data normally.

Request:
```
CQL=type="page" and space = "UM" and  label = 192
```

Result:
```
{  
   "results":[  
      { ...  },
      { ... },
      { ... },
      { ... },
      { ... }
   ],
   "start":0,
   "limit":10,
   "size":5,
   "_links":{  
      "self":"...",
      "base":"https://infomedia-test.gipmbh.de",
      "context":""
   }
}
```

Also, when I fake your Confluence by returning this JSON, I have my custom field working:

<img width="1118" alt="Screenshot 2019-06-05 at 20 19 40" src="https://user-images.githubusercontent.com/18350871/58976093-5412a980-87cf-11e9-9b86-b5046fa40b6e.png">

**Comment by mesilat** [comment] 2019-06-05 17:59
The resulting JSON is pre-processed by auiSelect2 `results` function. Let's take some logs from this function:

```
        $input.auiSelect2({
            multiple: true,
            ajax: {
                url: AJS.params.baseURL + '/rest/confield/1.0/field/' + $input.attr('id').substr(12) + '/pages',
                dataType: 'json',
                data: function(text){
                    var $form = $input.closest('form[name="jiraform"]');
                    if ($form.length > 0){
                        updateFilterFields($form);
                    }
                    //console.debug('com-mesilat-confields updateField() filterFields: ', JSON.stringify(filterFields));
                    return {
                        q: text,
                        'max-results': 10,
                        'filter-fields': JSON.stringify(filterFields)
                    };
                },
                results: function(data){
                    try {
                        var result = {
                            start: data.start,
                            limit: data.limit,
                            size: data.size,
                            results: Util.convertData(data.results)
                        };
                        console.debug('com-mesilat-confields $input.auiSelect2 results:', JSON.stringify(result));
                        return result;
                    } catch(e){
                        console.debug('com-mesilat-confields $input.auiSelect2 error:', e);
                    }
                },
                delay: 250
            },
            initSelection: function(input, callback){
                callback(initial);
            }
        });
```

If browser logs show no error in this function then I think there should be some other browser error that affects select2 behaviour. And this should be reflected in browser logs as well.

Please try version 1.0.6 and take some browser logs.

By the way, what JIRA version do you use?

**Comment by gcuny** [comment] 2019-06-06 08:30
I use the JIRA version 7.13.3 and the Confluence version 6.13.4.

Let me resume the erroneous behaviour of the Confluence Custom Field in my installation:
1) the simple CQL filter
	space = "UM" and  label = 192
   shows the expected results. --> OK
2) the CQL filter
	space = "UM" and  label = ${customfield_13520.value}
   shows the expected results for the initially selected option in the customfield_13520. --> OK
3) the CQL filter
	space = "UM" and  label = ${customfield_13520.value}
   does not show the expected results after the selected option in the customfield_13520 was changed. It always returns the results for the initially selected option in the customfield_13520. --> NOK

The problem in the Confluence Field is, that ${customfield_13520.value} returns the value stored for the issue in the data base, whereas it should return the transient value selected in the active modal screen. That's what I tried to show you on page 2 of my document Feedback_01-Version_1.0.2.pdf.

Here are some requested browser logs, but as expected, they do not show any errors concerning the confluence custom field:

[BrowserLog_02_Chrome_Version_1.0.6.txt](https://github.com/mesilat/confluence-fields/files/3260688/BrowserLog_02_Chrome_Version_1.0.6.txt)
[BrowserLog_01_Edge_Version_1.0.6.txt](https://github.com/mesilat/confluence-fields/files/3260689/BrowserLog_01_Edge_Version_1.0.6.txt)

Good luck,
Georges

**Comment by mesilat** [comment] 2019-06-10 19:59
Hi, Georges I tried to reproduce the problem you described. I installed a trial Confluence/JIRA Core pair and created a test setup. https://conftest.mesilat.comhttps://jiratest.mesilat.com Both can be accessed with gcuny / Bf4p17oE credentials. Take issue https://jiratest.mesilat.com/browse/TP-8 for example: "Product Group" field is set to "192". When I open the issue for editing I can select "Product D" because it has label "192" in Confluence. When I change "Product Group" to "191" I can select "Product B" because it has label "191" in Confluence. This does not require saving the issue. The value of the "Product Group" is taken from modal form. Can you help me reproduce the issue you described in my setup? Thank you Regards,Vladislav Babin        06.06.2019, 11:30, "gcuny" <notifications@github.com>:I use the JIRA version 7.13.3 and the Confluence version 6.13.4.
Let me resume the erroneous behaviour of the Confluence Custom Field in my installation:

the simple CQL filter
space = "UM" and  label = 192
shows the expected results. --> OK
the CQL filter
space = "UM" and  label = ${customfield_13520.value}
shows the expected results for the initially selected option in the customfield_13520. --> OK
the CQL filter
space = "UM" and  label = ${customfield_13520.value}
does not show the expected results after the selected option in the customfield_13520 was changed. It always returns the results for the initially selected option in the customfield_13520. --> NOK

The problem in the Confluence Field is, that ${customfield_13520.value} returns the value stored for the issue in the data base, whereas it should return the transient value selected in the active modal screen. That's what I tried to show you on page 2 of my document Feedback_01-Version_1.0.2.pdf.
Here are some requested browser logs, but as expected, they do not show any errors concerning the confluence custom field:
BrowserLog_02_Chrome_Version_1.0.6.txt
BrowserLog_01_Edge_Version_1.0.6.txt
Good luck,
Georges

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
-- Best regards,Mesilat Limited Teamsupport@mesilat.com

**Comment by gcuny** [comment] 2019-06-11 09:34
Hi Vladislav,

I can't reproduce the behaviour in your original environment.

But I found out, that the behaviour in my environment is due to the fact, that I switched off the 'inline edit mode' for the current project.
I did this in your project as well:
 - I changed the Issue Permissions: Edit Issues = none
 - Workflow: I added an 'Edit'-Button for the status 'To Do'.
Now you can reproduce the behaviour in your environement: display TP-8 (the Product Group is 192), click the Edit-Button (opens a modal dialog), Click the 'Product'-field: 3 options can be selected, Change the Product Group to 191, Click the 'Product'-field: the very same 3 opions as for 192 can be selected.

Regards, Georges

**Comment by mesilat** [comment] 2019-06-11 18:20
Hi,
I think you spotted it: the problem is that the addon was looking for form data `form[name="jiraform"]`. Quite unexpectedly the modifications you made removed the attribute `name` from tag `form`. So, to fix the issue I made a simple modification:
```
                    //var $form = $input.closest('form[name="jiraform"]');
                    var $form = $input.closest('form');
```
Please try version 1.0.7 at https://github.com/mesilat/confluence-fields/releases/tag/1.0.7
Regards,
Vladislav

**Comment by gcuny** [comment] 2019-06-12 06:30
Hi Vladislav,

great, now the improved CQL filter works as expected, at least for select lists (I didn't test anything else yet). Thank you very much.

Now, would you please tell me, how I can access the content and properties of a Confluence Field from a Groovy Script in a post function, for example. I'm not shure if I can trigger the appropriate event for any type of fields in Groovy, but I would like to clear the content of the Confluence Field, if the user changes the selection (or the input) in the field referenced in the CQL filter.

The current Confluence Field accepts the selectuion of multiple titles of Confluence pages. A further requirement would be, to have an option for the Confluence Field which restricts the number of accepted selections to one.

Should I open new tickets for the requirements above?

Do you have any plans for further improvements to the 'Confluence Custom Fields' App?

Regards,
Georges

**Comment by mesilat** [comment] 2019-06-12 08:21
Hi, good to know it finally works as expected

> how I can access the content 

Well, you can use JIRA API to access the issue:

```
GET api/2/issue/{issueIdOrKey}
```

Confluence field values are stored as JSON-like string:
```
 "customfield_11300": "{\"id\":\"24281132\",\"title\":\"Product 101\"},{\"id\":\"24281134\",\"title\":\"Product 102\"}",
```

You can parse the value into JSON array:
```
JSON.parse('[' + issue.customfield_11300 + ']');
```
> how I can access the ... properties 

The only metadata the plugin stores for a custom field is Confluence link id and CQL-filter:

`.../rest/confield/1.0/settings/{fieldId}`

For example:

```
GET http://127.0.0.1/jira/rest/confield/1.0/settings/11205

{
"id": 11205,
"filter": "space=\"RD\" and label=\"ref-product\"",
"confluenceId": "ce4fa217-8616-33cd-bbdd-c70af8d69196"
}
```

>  I would like to clear the content of the Confluence Field, if the user changes the selection (or the input) in the field referenced in the CQL filter

This requires some updates to the addon. I think I could make it a default behaviour while keeping old field values could be enabled by some option in field settings, don't you think so?

> to have an option for the Confluence Field which restricts the number of accepted selections to one.

Once again, this could be a settings option to switch between multi / single value

> Do you have any plans for further improvements to the 'Confluence Custom Fields' App?

Yes, of course. And I appreciate your feedback ;)

> Should I open new tickets for the requirements above?

Yes please. This one is long enough. However don't close it yet: there are some issues with replacement variables that break issue search that I have to fix yet

**Comment by gcuny** [comment] 2019-06-14 09:25
Hi Vladislav,
thank you very much for your detailed description on how to access the value and the metadata of a Confluence Field.
As you requested, I created 2 new issues with potential improvements to your APP.
Best regards,
Georges

**Comment by mesilat** [comment] 2019-06-19 11:48
Hi Georges Sorry for delay. I had to fix multiple issues with change history log for confluence fields which turned into a big redesign. Please check version 1.0.8. In this version there are two options added to configuration: - select multi that enables/disables multiple pages for a field- auto filter that can be used to clear selected pages once referenced field value changes The latter works as this: when the plugin encounters that referenced value was modified it executes query to get a new list of pages. If currently selected page is not in the list then it is removed from the field. On the other hand, if a page IS in the list it will be retained, so the field is not totally cleared, but only pages that do not match the new query are removed. It is thus somewhat different from what you requested -- let me know if this is a problem or not. Regards,Vladislav BabinMesilat Limited14.06.2019, 12:25, "gcuny" <notifications@github.com>:Hi Vladislav,
thank you very much for your detailed description on how to access the value and the metadata of a Confluence Field.
As you requested, I created 2 new issues with potential improvements to your APP.
Best regards,
Georges

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
-- Best regards,Mesilat Limited Teamsupport@mesilat.com

**Comment by gcuny** [comment] 2019-06-19 14:56
Hi Vladislav,
no problem with the delay; this is not a high priority task for me.
The function you described is OK for me, but unfortunately the version 1.0.8 does not do what you described. The options shown for the confluence field are not updated if I change the content of the field referenced in the filter and the options I select in the confluence field are not stored, if I close my modal screen. Please note, that I am in a modal screen and that inline editing is disabled. 
Regards,
Georges

**Comment by mesilat** [comment] 2019-06-20 17:03
Hi, Georges Please check version 1.0.9 It fixes the bugI have restarted the test zone: https://jiratest.mesilat.com and found that JIRAv8 behaves differently to JIRAv7 I used for development, sorry for that. Regards,Vladislav Babin 19.06.2019, 17:58, "gcuny" <notifications@github.com>:Hi Vladislav,
no problem with the delay; this is not a high priority task for me.
The function you described is OK for me, but unfortunately the version 1.0.8 does not do what you described. The options shown for the confluence field are not updated if I change the content of the field referenced in the filter and the options I select in the confluence field are not stored, if I close my modal screen. Please note, that I am in a modal screen and that inline editing is disabled.
Regards,
Georges

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
-- Best regards,Mesilat Limited Teamsupport@mesilat.com

**Comment by gcuny** [comment] 2019-06-24 14:11
Hi Vladislav,
I did some tests in your environment with version 1.0.9.2. Congratulations: here the Code does what I would expect it to do.
I also did some tests in my environment with version 1.0.9. I couldn't notice any differences to the behaviour of version 1.0.8. Sorry.
Regards,
Georges

**Comment by mesilat** [comment] 2019-06-25 06:28
Hi, Georges This is weird. I've setup another JIRA test site: https://jiratest-7-13-1.mesilat.com/ It does not fully match your version (which is 7.13.3 as you mentioned), but it is the closest match I could find  in docker hub.Autofiltering works as expected with this version. To investigate further into your issue I added some more browser logging to version 1.0.10 Please use console filter "com-mesilat-confields auto-filter". It should print something like this (screenshot from jiratest-7-13-1):  What auto-filter option does internally is: - bind to referenced field "change" event (the line with 'new value=' is printed when the event is fired)- create a new filter object to be used with CQL (the line with 'filter=')- query Confluence to check if currently selected pages are valid for the filter (the line with 'valid pages=')- fix the field to match valid options (the line with 'init selection=' and 'values=') Could you please provide this type of log from your environment? Regards,Vladislav24.06.2019, 17:11, "gcuny" <notifications@github.com>:Hi Vladislav,
I did some tests in your environment with version 1.0.9.2. Congratulations: here the Code does what I would expect it to do.
I also did some tests in my environment with version 1.0.9. I couldn't notice any differences to the behaviour of version 1.0.8. Sorry.
Regards,
Georges

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
-- Best regards,Mesilat Limited Teamsupport@mesilat.com

**Comment by gcuny** [comment] 2019-06-25 14:15
Hi Vladislav,
I don't know why, but suddenly the versions 1.0.9 and 1.0.10 seem to work in my environment, whereas the Version in your jiratest-7-13-1 doesn't: the input I produced in TP-7 should not be possible.
If I should encounter new problems in my environment I'll inform you.
By the way: I'm not able to save the browser logs any more (Chrome and Edge); could you please give me a hint? Thanks.
Regards,
Georges

**Comment by mesilat** [comment] 2019-06-25 15:02
Hi, Georges > the input I produced in TP-7 should not be possible. So far I can imagine two options to reproduce this behaviour: 1) Using inline edit. Just changing Product Group = 192 to 191 in inline edit will not remove violating Products2) Fast saving the issue immediately after changing Product Group to 191 -- before the background 'change' event handler is done. It is possible to solve both: to fix #1 -- disabling inline editing could help as well as some server-side processing of user input to clear the violating Products from the issueto fix #2 -- I could just disable issue save button until event handlers are done I will post update. > I'm not able to save the browser logs any more (Chrome and Edge); could you please give me a hint As a wild guess -- can it be an active filter that prevents your from viewing logs? Anyway I think that just restarting your browser would help :) 25.06.2019, 17:15, "gcuny" <notifications@github.com>:Hi Vladislav,
I don't know why, but suddenly the versions 1.0.9 and 1.0.10 seem to work in my environment, whereas the Version in your jiratest-7-13-1 doesn't: the input I produced in TP-7 should not be possible.
If I should encounter new problems in my environment I'll inform you.
By the way: I'm not able to save the browser logs any more (Chrome and Edge); could you please give me a hint? Thanks.
Regards,
Georges

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
-- Best regards,Mesilat Limited Teamsupport@mesilat.com

**Closed** 2019-09-13 12:01 UTC

**Comment by tetteroo** [comment] 2019-11-05 12:02
The online documentation of this feature uses the wrong syntax {$...} instead of ${...} to define the substitution variables.

**Comment by mesilat** [comment] 2019-11-06 15:02
> The online documentation of this feature uses the wrong syntax {$...} instead of ${...} to define the substitution variables.

Sorry for that. Fixed the docs
