### ISSUE TITLE
Test Search in Field configuration is OK / Search in Issue don´t work

### ISSUE THREAD

**Issue by zstetinova** [mesilat/confluence-fields#9] opened 2019-11-13 14:25 UTC
Hi,
can you help me whith this Problem pleace? Testsearch in my confluence Field configuration works , but in Issueform don´t. It is Textarea only.

Thank you
Zlatica

**Comment by mesilat** [comment] 2019-11-13 15:44
Hi,
Could you please provide:
- plugin version
- your JIRA version
- screenshot of custom fields configuration (where you say it works)
- screenshot of issue page (where it doesn't)
- and finally browser logs with errors if any

Regards,
Vladislav Babin

**Comment by zstetinova** [comment] 2019-11-14 09:26
Hi Vladislav,
**plugin version** - 1.0.16
**your JIRA version** -  8.1.0
**screenshot of custom fields configuration** 
![image](https://user-images.githubusercontent.com/57717260/68843351-3de70e80-06c8-11ea-849c-f49f77c4b952.png)
![image](https://user-images.githubusercontent.com/57717260/68843374-493a3a00-06c8-11ea-84f2-351fc1e6cb73.png)
**screenshot of issue page** 
![image](https://user-images.githubusercontent.com/57717260/68843441-6969f900-06c8-11ea-847b-bd9cccf41b6c.png)
**and finally browser logs** 
![browser logs](https://user-images.githubusercontent.com/57717260/68843572-a504c300-06c8-11ea-8af1-7f82431772cf.PNG)

Regards,
Zlatica

**Comment by mesilat** [comment] 2019-11-15 08:10
Hi,
Is this a Service Desk form or mobile or some custom form in JIRA? The plugin so far works only with standard issue create / edit forms. Could you show browser URL as well?

Regards,
Vladislav

**Comment by zstetinova** [comment] 2019-11-15 08:16
Hi,
here whit form URL:
![image](https://user-images.githubusercontent.com/57717260/68927624-76e6b800-0788-11ea-87c0-e7f8cf083ed3.png)

https://jira-test.reichhart.eu/plugins/servlet/desk/portal/16/create/273

Regards, 
Zlatica

**Comment by mesilat** [comment] 2019-11-15 08:20
I guess this is a customer portal.
The plugin will not work with it. I could fix this but it will take a week or two

Regards,
Vladislav

**Comment by zstetinova** [comment] 2019-11-15 08:26
Dear Vladislav,
that would be perfect!
Thank you
Regards,
Zlatica

**Comment by zstetinova** [comment] 2019-12-04 08:33
Hi Vladislav,
How does it look like?
Could you fix the plugin?

Best Regards
Zlatica

**Comment by mesilat** [comment] 2019-12-06 15:29
Hi,
Sorry, but I am still working on it. The addon works in Servicedesk normal issue view/edit, but not in customer portal. The problem is that portal does not use templates that I specify to render the custom field. There should be a way to overcome this limitation, though.

**Comment by mesilat** [comment] 2019-12-06 15:34
There's yet another issue with customer portal: more often than not customer portal users will not have an account in Confluence. Having an account is currently required to let user get data from Confluence instance. Thus serving data to customer portal will probably imply some kind of data caching in JIRA. Which is not implemented so far

**Comment by zstetinova** [comment] 2019-12-09 07:45
Hi Vladimir,
thank you very much for your Answer. In our company, all our customer portal users have or will have Confluence Account. 

Best Regards 
Zlatica

**Comment by mesilat** [comment] 2019-12-12 14:39
Hi, Zlatica

Sorry for keeping you waiting. However I have some good news for you: the latest hotfix ( https://github.com/mesilat/confluence-fields/releases/tag/1.0.17 ) now supports JSD Customer Portal. When you install the hotfix you may need to check the "As Definer" checkbox in a field configuration page, so that the plugin will use the definer (JIRA admin who defines the custom field) credentials to access Confluence data.

There are yet some issues with the Customer portal support: substitution variables are not working, not all tests passed. Hopefully this will be fixed by the beginning of the next week.

Regards,
Vladislav

**Comment by zstetinova** [comment] 2019-12-16 15:03
Hi Vladislav,
I installed and tested Fix - it works :-). Thanks for that. However, not all results that meet the CQL Fiter condition are shown to me. Are there any restrictions, rules - for example max number of results, sorting?

Regards
Zlatica

**Comment by mesilat** [comment] 2019-12-16 16:24
Hi, Zlatica

Yes, it does limit the number of results to 10:

```
        return {
          q: text,
          'max-results': 10,
          'filter-fields': JSON.stringify(filterFields)
        };
```

Did you try to type a substring? This should limit the number of matching pages, so you will end up with the page you are looking for.

**Comment by mesilat** [comment] 2019-12-19 11:04
Hi, Zlatica
Did this help? Do you still have issues with fields?

**Comment by zstetinova** [comment] 2019-12-19 12:35
Hi Vladimir,
sorry for delay, we had infrastructure troubles, i couldn´t test it - only now. The search with substring (min. 3 Charakters) or substring and * works. I write it in the documentation for users.

Thank you again very much for your help
Issue can be closed.

Best Regards
Zlatica

**Comment by mesilat** [comment] 2019-12-19 12:54
Good. Thanks for your feedback

**Closed by mesilat** 2019-12-19 12:54 UTC
